### ISSUE TITLE
Is it possible to use multiple CodingKeys for a single property?

### ISSUE THREAD

**Issue by umairsuraj** [marksands/BetterCodable#10]
`struct Foo: Decodable {
    enum CodingKeys: String, CodingKey {
        case contentIDs = "contentIds" || "Ids" || "IDs" // something like this?
    }
    let contentIDs: [UUID]
}`

**Comment by marksands** [comment]
Unfortunately, no. CodingKeys uses some magic that isn't possible to be modified through property wrappers or otherwise, so defining custom coding keys just doesn't work.

**Comment by umairsuraj** [comment]
> Unfortunately, no. CodingKeys uses some magic that isn't possible to be modified through property wrappers or otherwise, so defining custom coding keys just doesn't work.

Cann't we do something like:

`extension KeyedDecodingContainer where K == AnyKey {
    func decode<T>(_ type: T.Type, forMappedKey key: String, in keyMap: [String: [String]]) throws -> T where T : Decodable{
        for key in keyMap[key] ?? [] {
            if let value = try? decode(T.self, forKey: AnyKey(stringValue: key)) { 
                return value
            }
        }
        return try decode(T.self, forKey: AnyKey(stringValue: key))
    }
}`

**Comment by umairsuraj** [comment]
It's very important feature that i am searching for everywhere.

I have two different JSONs from two different countries with two different languages with different keys.

**Comment by marksands** [comment]
You could probably get by with using something like that to facilitate what you're looking for, but if you want the boilerplate in a property wrapper then I don't think it's possible yet. Since `Decodable` relies on an initializer to decode, `init(from decoder: Decoder) throws`, there's no way to pass a custom string since that would be a separate initializer. I'd love to solve this problem, though, if there's a supported way to make it happen!
